<a href="https://colab.research.google.com/github/Muhammad-Awaix/-ML-Pyhton-Projects/blob/main/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
SIZE = 4
matrix = []
for i in range(SIZE):
    row = []
    for j in range(SIZE):
        row.append(0)
    matrix.append(row)

for row in matrix:
    print(' '.join(map(str, row)))

0 0 0 0
0 0 0 0
0 0 0 0
0 0 0 0

In [ ]:
count = 0
for i in "Banana":
    if i == "a":
        count+=1
print(count)

3

In [ ]:
s = "PYTHON"
rev = ""
for ch in s:
    rev = ch + rev
print(rev)

NOHTYP

In [ ]:
student = {"Name":"Awais", "Age":25, "Grade":"A"}

for key in student:
    print(key)
print()
for values in student:
    print(student[values])
print()
for keys in student:
    print(f"{keys}: {student[keys]}")
print()
print(f"Name: {student.get('Name',' ')} | Grade: {student.get('Grade'," ")}")
# ' ' for default value

Name
Age
Grade

Awais
25
A

Name: Awais
Age: 25
Grade: A

Name: Awais | Grade: A

In [ ]:
num = [10, 15, 20, 25, 30, 35, 40]

result = [x**2 for x in num if x % 2 == 0]
print(result)  # [100, 400, 900, 1600]

[100, 400, 900, 1600]

In [ ]:
print('My favorite colors are', 'blue', 'green', 'red')

My favorite colors are blue green red

In [ ]:
# freecodecamp exe
name = 'Alice'
print(name, type(name))

is_student = True
print(is_student, type(is_student))

age = 20
print(age, type(age))

score = 80.5
print(isinstance(score, float))
print(score, type(score))

my_str = 'hello world'

split_words = my_str.split()
print(split_words)  # ['hello', 'world']

my_list = ['hello', 'world']

joined_my_str = ' '.join(my_list)
print(joined_my_str)  # hello world

In [ ]:
# freecodecamp
first_name = 'John'
last_name = 'Doe'
full_name = first_name + ' ' + last_name

address = '123 Main Street'
address += ', Apartment 4B'

employee_age = 28
employee_info = full_name + ' is ' + str(employee_age) + ' years old'
print(employee_info)

experience_years = 5
experience_info = 'Experience: ' + str(experience_years) + ' years'
print(experience_info)

position = 'Data Analyst'
salary = 75000
employee_card = f'Employee: {full_name} | Age: {employee_age} | Position: {position} | Salary: ${salary}'
print(employee_card)

employee_code = 'DEV-2026-JD-001'
department = employee_code[0:3]
print(department)
year_code = employee_code[4:8]
print(year_code)
initials = employee_code[9:11]
print(initials)
last_three = employee_code[-3:]
print(last_three)

In [ ]:
#freecodecamp
base_price = 15
age = 21
seat_type = 'Gold'
show_time = 'Evening'

if age > 17:
    print('User is eligible to book a ticket')

if age >= 21:
    print('User is eligible for Evening shows')
else:
    print('User is not eligible for Evening shows')

is_member = False
is_weekend = False

discount = 0
if is_member and age >= 21:
    discount = 3
    print('User qualifies for membership discount')
else:
    print('User does not qualify for membership discount')
print('Discount:', discount)

extra_charges = 0
if is_weekend or show_time == 'Evening':
    extra_charges = 2
    print('Extra charges will be applied')
else:
    print('No extra charges will be applied')
print('Extra charges:', extra_charges)

if age >= 21 or age >= 18 and (show_time != 'Evening' or is_member):
    print('Ticket booking condition satisfied')

    service_charges = 0
    if seat_type == 'Premium':
        service_charges = 5
    elif seat_type == 'Gold':
        service_charges = 3
    else:
        service_charges = 1
    print('Service charges:', service_charges)
    final_price = extra_charges+service_charges+base_price-discount
    print('Final price of ticket:', final_price)
else:
    print('Ticket booking failed due to restrictions')

In [ ]:
#freeCodeCamp
def caesar(text, shift, encrypt=True):

    if not isinstance(shift, int):
        return 'Shift must be an integer value.'

    if shift < 1 or shift > 25:
        return 'Shift must be an integer between 1 and 25.'

    alphabet = 'abcdefghijklmnopqrstuvwxyz'

    if not encrypt:
        shift = - shift

    shifted_alphabet = alphabet[shift:] + alphabet[:shift]
    translation_table = str.maketrans(alphabet + alphabet.upper(), shifted_alphabet + shifted_alphabet.upper())
    encrypted_text = text.translate(translation_table)
    return encrypted_text

def encrypt(text, shift):
    return caesar(text, shift)

def decrypt(text, shift):
    return caesar(text, shift, encrypt=False)

encrypted_text = 'Pbhentr vf sbhaq va hayvxryl cynprf.'

decrypted_text = decrypt(encrypted_text, 13)

print(decrypted_text)

In [ ]:
def create_character(name, strength, intelligence, charisma):
    # Name Validations
    if not isinstance(name, str):
        return "The character name should be a string"
    if name == "":
        return "The character should have a name"
    if len(name) > 10:
        return "The character name is too long"
    if " " in name:
        return "The character name should not contain spaces"

    # Stat Type Validation — exclude booleans, they are subclass of int in Python
    if (not isinstance(strength, int) or isinstance(strength, bool) or
        not isinstance(intelligence, int) or isinstance(intelligence, bool) or
        not isinstance(charisma, int) or isinstance(charisma, bool)):
        return "All stats should be integers"

    # Stat Range Validations
    if strength < 1 or intelligence < 1 or charisma < 1:
        return "All stats should be no less than 1"
    if strength > 4 or intelligence > 4 or charisma > 4:
        return "All stats should be no more than 4"

    # Points Sum Validation
    if strength + intelligence + charisma != 7:
        return "The character should start with 7 points"

    # Character Sheet Generation
    full_dot = '●'
    empty_dot = '○'

    str_bar = (full_dot * strength) + (empty_dot * (10 - strength))
    int_bar = (full_dot * intelligence) + (empty_dot * (10 - intelligence))
    cha_bar = (full_dot * charisma) + (empty_dot * (10 - charisma))

    return f"{name}\nSTR {str_bar}\nINT {int_bar}\nCHA {cha_bar}"
create_character("ren", 1, 2, 4)

'ren\nSTR ●○○○○○○○○○\nINT ●●○○○○○○○○\nCHA ●●●●○○○○○○'

In [ ]:
# List
numbers = [1, 2, 3, 4, 5]
even_numbers = [6, 8, 10]
numbers.append(even_numbers)
print(numbers)

n_l = list("Awais")
print(n_l)
n_1 = ''.join(n_l)
n_1

[1, 2, 3, 4, 5, [6, 8, 10]]
['A', 'w', 'a', 'i', 's']

'Awais'

In [ ]:
numbers.extend(even_numbers)
print(numbers)

[1, 2, 3, 4, 5, [6, 8, 10], 6, 8, 10]

In [ ]:
numbers.insert(2, 2.6)
print(numbers)
numbers.remove([6,8,10])
print(numbers)

[1, 2, 2.6, 2.6, 3, 4, 5, [6, 8, 10], 6, 8, 10]
[1, 2, 2.6, 2.6, 3, 4, 5, 6, 8, 10]

In [ ]:
numbers.reverse()
print(numbers)

[10, 8, 6, 5, 4, 3, 2.6, 2.6, 2, 1]

In [ ]:
programming_languages = ['Rust', 'Java', 'Python', 'C++']
programming_languages.index('Python')

2

In [ ]:
# Tuples
developer = ('Alice', 34, 'Rust Developer')
name, age, job = developer
name, *rest = developer
print(name)
print(age)
print(rest)

Alice
34
[34, 'Rust Developer']

In [ ]:
# count(), index()
programming_languages = ('Rust', 'Java', 'Python', 'C++', 'Rust', 'Python')
programming_languages.index('Python', 3)

5

In [ ]:
#Loops
secret_number = 3
guess = 0

while guess != secret_number:
    guess = int(input('Guess the number (1-5): '))
    if guess != secret_number:
        print('Wrong! Try again.')

print('You got it!')

In [ ]:
words = ['sky', 'apple', 'rhythm', 'fly', 'orange']

for word in words:
    for letter in word:
        if letter.lower() in 'aeiou':
            print(f"'{word}' contains the vowel '{letter}'")
            break
    else:
        print(f"'{word}' has no vowels")

'sky' has no vowels
'apple' contains the vowel 'a'
'rhythm' has no vowels
'fly' has no vowels
'orange' contains the vowel 'o'

In [ ]:
for num in range(2, 11, 2):
    print(num, end = ' ')

2 4 6 8 10

In [ ]:
languages = ['Spanish', 'English', 'Russian', 'Chinese']
for index, lang in enumerate(languages):
    print(f"{index}: {lang}")
list(enumerate(languages))

0: Spanish
1: English
2: Russian
3: Chinese

[(0, 'Spanish'), (1, 'English'), (2, 'Russian'), (3, 'Chinese')]

In [ ]:
developers = ['Naomi', 'Dario', 'Jessica', 'Tom']
ids = [1, 2, 3, 4]
print(list(zip(ids, developers)))
print()
for name, id in zip(developers, ids):
    print(f'Name: {name}')
    print(f'ID: {id}')

[(1, 'Naomi'), (2, 'Dario'), (3, 'Jessica'), (4, 'Tom')]

Name: Naomi
ID: 1
Name: Dario
ID: 2
Name: Jessica
ID: 3
Name: Tom
ID: 4

In [ ]:
#  List Comprehensions
even_numbers = [num for num in range(21) if num %2==0]
print(even_numbers)
result = [(num, 'even') if num %2==0 else (num, 'odd') for num in range(1,9)]
print(result)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[(1, 'odd'), (2, 'even'), (3, 'odd'), (4, 'even'), (5, 'odd'), (6, 'even'), (7, 'odd'), (8, 'even')]

In [ ]:
#01 filter
words = ['tree', 'sky', 'mountain', 'river', 'cloud', 'sun']
def is_long_word(word):
    return len(word)>4
long_words = list(filter(is_long_word, words))
print(long_words)
print()
#02 filter
celsius = [0, 10, 20, 30, 40]
def to_fahrenheit(temp):
    return (temp * 9/5) + 32
fahrenheit = list(map(to_fahrenheit, celsius))
print(fahrenheit)

['mountain', 'river', 'cloud']

[32.0, 50.0, 68.0, 86.0, 104.0]

In [ ]:
numbers = [5, 10, 15, 20]
total = sum(numbers, start=10)
print(total) # ?

60

In [ ]:
# lambda function
numbers = [1, 2, 3, 4, 5]
even_numbers = list(filter(lambda x:x%2==0, numbers))
print(even_numbers)


square = lambda x: x ** 2
squared_numbers = list(map(square, numbers))
print(squared_numbers)

[2, 4]
[1, 4, 9, 16, 25]

In [ ]:
#freecodecamp
def pin_extractor(poems):
    secret_codes = []
    for poem in poems:
        secret_code = ''
        lines = poem.split('\n')
        for line_index, line in enumerate(lines):
            words = line.split()
            if len(words) > line_index:
                secret_code += str(len(words[line_index]))
            else:
                secret_code += '0'
        secret_codes.append(secret_code)
    return secret_codes

poem = """Stars and the moon
shine in the sky
white and
until the end of the night"""

poem2 = 'The grass is green\nhere and there\nhoping for rain\nbefore it turns yellow'
poem3 = 'There\nonce\nwas\na\ndragon'

print(pin_extractor([poem,poem2, poem3]))

In [ ]:
def number_pat(n):
    if isinstance(n, int):
        for number in range(1, n+1):
            print(number)
number_pat(4)

1
2
3
4

In [ ]:
def number_pattern(n):
    if not isinstance(n, int):
        return 'Argument must be an integer value.'
    if n < 1:
        return 'Argument must be an integer greater than 0.'
    result = ''
    for pat in range(1, n+1):
        result += str(pat) + ' '
    return result.strip()

In [ ]:
numbers = [1, 2, 3, 4, 5, 5, 5]
numbers.remove(5)

print(numbers)

[1, 2, 3, 4, 5, 5]

In [ ]:
product = dict([('resturent','PapaChenos'), ('Deal1','BurgerFrize'), ('Price',12.5), ('Toppings',['mozzarella', 'basil'])])
print(product)

{'resturent': 'PapaChenos', 'Deal1': 'BurgerFrize', 'Price': 12.5, 'Toppings': ['mozzarella', 'basil']}

In [ ]:
print(type(product))
print(product.keys())
print(product.values())
print(product.items())

<class 'dict'>
dict_keys(['resturent', 'Deal1', 'Price', 'Toppings'])
dict_values(['PapaChenos', 'BurgerFrize', 15, ['mozzarella', 'basil']])
dict_items([('resturent', 'PapaChenos'), ('Deal1', 'BurgerFrize'), ('Price', 15), ('Toppings', ['mozzarella', 'basil'])])

In [ ]:
product.update({'Price':15})

In [ ]:
products = {
    'Laptop': 990,
    'Smartphone': 600,
    'Tablet': 250,
    'Headphones': 70,
}
for product, price in products.items():
    products[product] = round(price * 0.8)
print(products)

{'Laptop': 792, 'Smartphone': 480, 'Tablet': 200, 'Headphones': 56}

In [ ]:
# Sets
my_set = {1, 2, 3, 4, 5}
print(my_set)
type(my_set)

{1, 2, 3, 4, 5}

set

In [ ]:
my_set.add(6)
print(my_set)

{1, 2, 3, 4, 5, 6}

In [ ]:
my_set = {1, 2, 3, 4, 5, 6}
your_set = {1, 3, 4, 5}
print(my_set.issubset(your_set))
print(my_set.issuperset(your_set))
print(my_set.intersection(your_set))
print(my_set.union(your_set))
print(my_set.difference(your_set))
print(your_set.difference(my_set))

False
True
{1, 3, 4, 5}
{1, 2, 3, 4, 5, 6}
{2, 6}
set()

In [ ]:
# Digiskills
class Dog:
    def speak(self):
        print("Woof")
class Cat:
    def speak(self):
        print("Maow")
for sound in [Dog(), Cat()]:
    sound.speak()

Woof
Maow

In [ ]:
class Calculate:
    def sum(self, a, b=0, c=0):
        return a+b+c

In [ ]:
cal1 = Calculate()
print(cal1.sum(1,2))
print(cal1.sum(4,5,6))

3
15

In [ ]:
#freecodecamp
import re

medical_records = [
    {
        'patient_id': 'P1001',
        'age': 34,
        'gender': 'Female',
        'diagnosis': 'Hypertension',
        'medications': ['Lisinopril'],
        'last_visit_id': 'V2301',
    },
    {
        'patient_id': 'p1002',
        'age': 47,
        'gender': 'male',
        'diagnosis': 'Type 2 Diabetes',
        'medications': ['Metformin', 'Insulin'],
        'last_visit_id': 'v2302',
    },
    {
        'patient_id': 'P1003',
        'age': 29,
        'gender': 'female',
        'diagnosis': 'Asthma',
        'medications': ['Albuterol'],
        'last_visit_id': 'v2303',
    },
    {
        'patient_id': 'p1004',
        'age': 56,
        'gender': 'Male',
        'diagnosis': 'Chronic Back Pain',
        'medications': ['Ibuprofen', 'Physical Therapy'],
        'last_visit_id': 'V2304',
    }
]

def find_invalid_records(
    patient_id, age, gender, diagnosis, medications, last_visit_id
):
    constraints = {
        'patient_id': isinstance(patient_id, str)
        and re.fullmatch('p\d+', patient_id, re.IGNORECASE),
        'age': isinstance(age, int) and age >= 18,
        'gender': isinstance(gender, str) and gender.lower() in ('male', 'female'),
        'diagnosis': isinstance(diagnosis, str) or diagnosis is None,
        'medications': isinstance(medications, list)
        and all([isinstance(i, str) for i in medications]),
        'last_visit_id': isinstance(last_visit_id, str)
        and re.fullmatch('v\d+', last_visit_id, re.IGNORECASE)
    }
    return [key for key, value in constraints.items() if not value]

def validate(data):
    is_sequence = isinstance(data, (list, tuple))

    if not is_sequence:
        print('Invalid format: expected a list or tuple.')
        return False

    is_invalid = False
    key_set = set(
        ['patient_id', 'age', 'gender', 'diagnosis', 'medications', 'last_visit_id']
    )

    for index, dictionary in enumerate(data):
        if not isinstance(dictionary, dict):
            print(f'Invalid format: expected a dictionary at position {index}.')
            is_invalid = True
            continue

        if set(dictionary.keys()) != key_set:
            print(
                f'Invalid format: {dictionary} at position {index} has missing and/or invalid keys.'
            )
            is_invalid = True
            continue

        invalid_records = find_invalid_records(**dictionary)
        for key in invalid_records:
            val = dictionary[key]
            print(f"Unexpected format '{key}: {val}' at position {index}.")
            is_invalid = True

    if is_invalid:
        return False
    print('Valid format.')
    return True

validate(medical_records)

In [ ]:
try:
    num = int(intput('Enter a number to divide'))
    print(10/num)
except ZeroDivisionError:
    print("Number must be greater then zero")
except ValueError:
    print("Number must be an integer")
except Exception as e:
    print("Some unexpacted happend")

Some unexpacted happend

In [ ]:
# Personal Finance Tracker
import os

# --- 1. OOPS: The Data Structure ---
class Transaction:
    """Represents a single financial record."""
    def __init__(self, category, amount, description):
        self.category = category
        self.amount = amount
        self.description = description

    def __str__(self):
        return f"[{self.category}] ${self.amount:.2f}: {self.description}"

# --- 2. FILE HANDLING & LOGIC ---
class FinanceTracker:
    def __init__(self, filename="finance_data.txt"):
        self.filename = filename
        self.transactions = []
        self.load_data()

    def load_data(self):
        """FILE HANDLING: Reads data from a file when the app starts."""
        if not os.path.exists(self.filename):
            return # No file yet, start fresh

        try:
            with open(self.filename, 'r') as file:
                for line in file:
                    # DATA TYPES: Splitting strings back into variables
                    cat, amt, desc = line.strip().split('|')
                    self.transactions.append(Transaction(cat, float(amt), desc))
        except (FileNotFoundError, ValueError) as e:
            print(f"Error loading data: {e}")

    def save_data(self):
        """FILE HANDLING: Overwrites the file with the current list."""
        with open(self.filename, 'w') as file:
            for t in self.transactions:
                file.write(f"{t.category}|{t.amount}|{t.description}\n")

    def add_transaction(self):
        """USER INPUT & EXCEPTION HANDLING."""
        print("\n--- Add New Transaction ---")
        category = input("Enter Category (e.g., Food, Rent, Salary): ").capitalize()
        description = input("Enter Description: ")

        # EXCEPTION HANDLING: Ensure the user enters a valid number
        try:
            amount = float(input("Enter Amount: "))
        except ValueError:
            print("❌ Invalid amount! Please enter a number (e.g., 10.50).")
            return

        # Adding the object to our list
        new_t = Transaction(category, amount, description)
        self.transactions.append(new_t)
        self.save_data()
        print("✅ Transaction added successfully!")

    def show_summary(self):
        """LOOPS & CONDITIONALS: Calculating totals."""
        if not self.transactions:
            print("\nNo records found.")
            return

        print("\n--- Financial Summary ---")
        total_balance = 0
        for t in self.transactions:
            print(t)
            total_balance += t.amount

        # CONDITIONALS: Dynamic feedback
        print("-" * 25)
        print(f"Total Balance: ${total_balance:.2f}")
        if total_balance < 0:
            print("⚠️ Warning: You are in debt!")
        else:
            print("💰 You are doing great!")

# --- 3. MAIN PROGRAM LOOP ---
def main():
    tracker = FinanceTracker()

    while True:
        print("\n=== SMART LEDGER ===")
        print("1. Add Transaction")
        print("2. View History & Summary")
        print("3. Exit")

        choice = input("Choose an option: ")

        if choice == '1':
            tracker.add_transaction()
        elif choice == '2':
            tracker.show_summary()
        elif choice == '3':
            print("Goodbye!")
            break
        else:
            print("❌ Invalid choice, try again.")

# BOILERPLATE: Standard starting point
if __name__ == "__main__":
    main()

=== SMART LEDGER ===
1. Add Transaction
2. View History & Summary
3. Exit
Choose an option: 1

--- Add New Transaction ---
Enter Category (e.g., Food, Rent, Salary): Online Transection
Enter Description: Purchase UC
Enter Amount: 1250
✅ Transaction added successfully!

=== SMART LEDGER ===
1. Add Transaction
2. View History & Summary
3. Exit
Choose an option: 2

--- Financial Summary ---
[Online transection] $1250.00: Purchase UC
-------------------------
Total Balance: $1250.00
💰 You are doing great!

=== SMART LEDGER ===
1. Add Transaction
2. View History & Summary
3. Exit
Choose an option: 1

--- Add New Transaction ---
Enter Category (e.g., Food, Rent, Salary): Loan
Enter Description: Pay App Loan
Enter Amount: 2250
✅ Transaction added successfully!

=== SMART LEDGER ===
1. Add Transaction
2. View History & Summary
3. Exit
Choose an option: 2

--- Financial Summary ---
[Online transection] $1250.00: Purchase UC
[Loan] $2250.00: Pay App Loan
-------------------------
Total Balance: $3500.00
💰 You are doing great!

=== SMART LEDGER ===
1. Add Transaction
2. View History & Summary
3. Exit
Choose an option: 3
Goodbye!

In [ ]:
print(abs(-5))

5

In [1]:
import numpy as np
print(np.ones((2,3)))
print()
print(np.array([1,2,3], dtype=float))
print()
print(np.full((2,3),7))
print()
print(np.arange(0,10,2))
print()
print(np.linspace(0,1,5))
print()
print(np.eye(4))
print()
print(np.diag([1,2,3]))

[[1. 1. 1.]
 [1. 1. 1.]]

[1. 2. 3.]

[[7 7 7]
 [7 7 7]]

[0 2 4 6 8]

[0.   0.25 0.5  0.75 1.  ]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1 0 0]
 [0 2 0]
 [0 0 3]]

In [2]:
a1 = [10, 20, 30]
a2 = [40, 50, 60]
a3 = [70, 80, 90]
metrix = np.array([a1, a2, a3])
print(metrix)
print()
print(metrix.shape)
print()
print(metrix.dtype)

[[10 20 30]
 [40 50 60]
 [70 80 90]]

(3, 3)

int64

In [3]:
print(metrix[1,1])
print(metrix[-1,-1])
print(metrix[0,:])
print(metrix[2,1:])
print(metrix[::2,::2])
metrix[-1,-1]=900

50
90
[10 20 30]
[80 90]
[[10 30]
 [70 90]]

In [4]:
metrix

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80, 900]])

In [5]:
copy_metrix = metrix[::]
hard_copy = metrix.copy()
print(copy_metrix)
print(hard_copy)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80 900]]
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80 900]]

In [6]:
metrix[0] = 101
print(copy_metrix)
print(hard_copy)

[[101 101 101]
 [ 40  50  60]
 [ 70  80 900]]
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80 900]]

In [7]:
import time
start = time.time()
squares = [x**2 for x in range(1, 1000000)]
end = time.time()
print(end-start)

0.1713712215423584

In [8]:
start = time.time()
arr  = np.arange(1000000)
squares  = arr**2
end = time.time()
print(end-start)

0.039112091064453125

In [14]:
import pandas as pd
ser = pd.Series([10,20,30,40,50], index=['a', 'b', 'c', 'd', 'e'])
print(ser)
print(ser.values)
print(ser.index)
print(ser.dtype)
print(ser.value_counts())

a    10
b    20
c    30
d    40
e    50
dtype: int64
[10 20 30 40 50]
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
int64
10    1
20    1
30    1
40    1
50    1
Name: count, dtype: int64

In [16]:
data = {
    "Name":['Awais', 'Ali', 'Umair', 'Rizwan'],
    "Age":[25, 27, 20, 30],
    "Status":[1, 1, 0, 1]
}
df = pd.DataFrame(data)
print(df)

     Name  Age  Status
0   Awais   25       1
1     Ali   27       1
2   Umair   20       0
3  Rizwan   30       1

In [1]:
import kagglehub
path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")
path

Using Colab cache for faster access to the 'creditcardfraud' dataset.

'/kaggle/input/creditcardfraud'

In [3]:
import pandas as pd
df = pd.read_csv('/kaggle/input/creditcardfraud/creditcard.csv')

In [4]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [5]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [27]:
df.shape

(284807, 31)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [29]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [36]:
print(df['Amount'].max())
print(df['Amount'].min())
print(df['Amount'].mean())
print(df['Amount'].mode())

25691.16
0.0
88.34961925093133
0    1.0
Name: Amount, dtype: float64

In [38]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [43]:
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy'],
    'age': [30, 24, 35, 29, 42, 50, 22, 38, 45, 31],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'],
    'salary': [70000, 60000, 85000, 72000, 95000, 110000, 58000, 90000, 100000, 78000]
}
df = pd.DataFrame(data)
print(df)
print()
print(df.loc[5:, ['name', 'age']])
print()
print(df.iloc[0:2, 1:3])

      name  age          city  salary
0    Alice   30      New York   70000
1      Bob   24   Los Angeles   60000
2  Charlie   35       Chicago   85000
3    David   29       Houston   72000
4      Eve   42       Phoenix   95000
5    Frank   50  Philadelphia  110000
6    Grace   22   San Antonio   58000
7    Heidi   38     San Diego   90000
8     Ivan   45        Dallas  100000
9     Judy   31      San Jose   78000

    name  age
5  Frank   50
6  Grace   22
7  Heidi   38
8   Ivan   45
9   Judy   31

   age         city
0   30     New York
1   24  Los Angeles

In [45]:
high_salary = df[df['salary']>70000]
high_salary

      name  age          city  salary
2  Charlie   35       Chicago   85000
3    David   29       Houston   72000
4      Eve   42       Phoenix   95000
5    Frank   50  Philadelphia  110000
7    Heidi   38     San Diego   90000
8     Ivan   45        Dallas  100000
9     Judy   31      San Jose   78000

In [46]:
df.loc[df['age']<40,'salary'] = 50000
df

      name  age          city  salary
0    Alice   30      New York   50000
1      Bob   24   Los Angeles   50000
2  Charlie   35       Chicago   50000
3    David   29       Houston   50000
4      Eve   42       Phoenix   95000
5    Frank   50  Philadelphia  110000
6    Grace   22   San Antonio   50000
7    Heidi   38     San Diego   50000
8     Ivan   45        Dallas  100000
9     Judy   31      San Jose   50000

In [9]:
# print(df.isnull().sum())
print(df.duplicated().sum())
df.drop_duplicates(inplace=True)

1081

In [10]:
print(df.duplicated().sum())

0

In [23]:
data = {'categories':['  Electronics', 'computer ', 'electronics', 'FURNITURE', 'COmputer', 'home-Appliences',
                      'Awais_fellow', 'ecommerace','Char_ger']}
df_1 = pd.DataFrame(data)

In [24]:
df_1['Clean_data'] = df_1['categories'].str.strip().str.lower().str.replace('[_-]', ' ', regex=True)
df_1

        categories       Clean_data
0      Electronics      electronics
1        computer          computer
2      electronics      electronics
3        FURNITURE        furniture
4         COmputer         computer
5  home-Appliences  home appliences
6     Awais_fellow     awais fellow
7       ecommerace       ecommerace
8         Char_ger         char ger